const TAGS = [
  "dp",
  "games",
  "brute force",
  "combinatorics",
  "constructive algorithms",
  "dfs and similar",
  "math",
  "bitmasks",
  "divide and conquer",
  "greedy",
  "interactive",
  "probabilities",
  "ternary search",
  "binary search",
  "data structures",
  "dsu",
  "implementation",
  "sortings",
  "two pointers",
  "graphs",
  "trees",
  "strings",
  "number theory",
  "geometry",
  "graph matchings",
  "meet-in-the-middle",
  "matrices",
  "*special",
  "fft",
  "flows",
  "shortest paths",
  "hashing",
  "chinese remainder theorem",
  "2-sat",
  "schedules",
  "string suffix structures",
  "expression parsing"
];
export default TAGS;